---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ instance_secret_name }}'
  namespace: '{{ namespace_name }}'
type: Opaque
data:
  # GitLab
  # ...

  # PostgreSQL
  postgresql-password: {{ existing_instance_secret['postgresql-password']|default(lookup('password', '/dev/null length=32')|b64encode) }}

  # Redis
  redis-password: {{ existing_instance_secret['redis-password']|default(lookup('password', '/dev/null length=32')|b64encode) }}

  # MDR-X application
  secret-key: {{ existing_instance_secret['secret-key']|default(lookup('password', '/dev/null length=32')|b64encode) }}

  # OAuth application
  social-auth-gitlab-key: "{{ social_auth_gitlab_key|b64encode }}"
  social-auth-gitlab-secret: "{{ social_auth_gitlab_secret|b64encode }}"

  # SMTP password, for GitLab
  smtp-password: "{{ smtp_password|default('')|b64encode }}"
