---
- hosts: all
  connection: local
  gather_facts: no

  roles:
    - role: cluster
      tags: cluster

  vars_prompt:
    - name: instance_name
      prompt: Which instance name?
      private: no

  tasks:
    - name: Get GitLab initial root password
      community.kubernetes.k8s_info:
        api_version: v1
        kind: Secret
        name: gitlab-gitlab-initial-root-password
        namespace: 'instance-{{ instance_name }}'
      register: gitlab_initial_root_password_secret

    - name: Extract initial root password from secret
      set_fact:
        initial_root_password: "{{ gitlab_initial_root_password_secret.resources.0.data.password|b64decode }}"

    - name: Display root password
      debug:
        msg: 'The initial GitLab root password for the {{ instance_name }} instance is: {{ initial_root_password }}'

  vars_files:
    - vaults/main.yml
    - 'vaults/environment/{{ environment }}.yml'
    - vars/main.yml
    - 'vars/environment/{{ environment }}.yml'
