apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
  namespace: '{{ namespace_name }}'
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: OnFailure
{% set pod_spec %}{% include "templates/mdrx-pod-spec.yml" with context %}{% endset %}
      {{ pod_spec|indent(6) }}
