apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ name }}'
  namespace: '{{ namespace_name }}'
  labels:
    app: '{{ name }}'
    instance: '{{ instance.id }}'
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: '{{ name }}'
      instance: '{{ instance.id }}'
  template:
    metadata:
      name: '{{ name }}'
      labels:
        app: '{{ name }}'
        instance: '{{ instance.id }}'

    spec:
{% set pod_spec %}{% include "templates/mdrx-pod-spec.yml" with context %}{% endset %}
      {{ pod_spec|indent(6) }}
